version: '3'

services:
  db:
    container_name: Kawinphak-postgres
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=Kawinphak
      - POSTGRES_PASSWORD=Kawinphak2003
    image: postgres:latest
    restart: unless-stopped

  pgadmin:
    container_name: Kawinphakpg-admin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=kawinphak-i@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=Kawinphak2003
    image: dpage/pgadmin4:latest

  strapi:
    container_name: Kawinphak-strapi
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=192.168.56.1
      - DATABASE_PORT=54322
      - DATABASE_NAME=strapi4
      - DATABASE_USERNAME=Kawinphak
      - DATABASE_PASSWORD=Kawinphak2003
      - DATABASE_SSL=false
    image: naskio/strapi:latest
